# Generated by Django 5.2.3 on 2025-07-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactus',
            name='subject',
        ),
        migrations.AddField(
            model_name='contactus',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
