# Generated by Django 5.2.3 on 2025-07-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0002_remove_contactus_subject_contactus_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='zip_code',
            field=models.CharField(max_length=10),
        ),
    ]
