# Generated by Django 5.2.3 on 2025-07-15 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0003_alter_contactus_zip_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contactus',
            name='zip_code',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
    ]
