# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('public', '0005_alter_contactus_zip_code'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactUs',
            new_name='contact_us',
        ),
    ]
