# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_clients', '0002_alter_clientuser_table'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientUser',
            new_name='users_clients',
        ),
    ]
