# Generated by Django 5.2.3 on 2025-07-07 17:07

import api.models.company
import api.models.contactus
import api.models.deliverychallan
import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.CharField(default=api.models.contactus.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=320)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.CharField(default=api.models.company.generate_unique_id, editable=False, max_length=11, primary_key=True, serialize=False, unique=True)),
                ('client_name', models.CharField(max_length=200)),
                ('contact_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('group', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='client_details', to='auth.group')),
            ],
            options={
                'verbose_name': 'Company',
                'verbose_name_plural': 'Companies',
                'db_table': 'companies',
            },
        ),
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.CharField(default=api.models.deliverychallan.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('challan_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('customer', models.CharField(max_length=200)),
                ('dc_summary', models.TextField(blank=True)),
                ('delivery_executives', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_submission', models.BooleanField(default=False)),
                ('proof_of_delivery', models.FileField(blank=True, null=True, upload_to='proof_of_delivery/')),
                ('pod_upload_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Challan',
                'verbose_name_plural': 'Delivery Challans',
                'db_table': 'delivery_challan',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='delivery_ch_date_810292_idx'), models.Index(fields=['customer'], name='delivery_ch_custome_913e3f_idx'), models.Index(fields=['created_at'], name='delivery_ch_created_7b8252_idx')],
            },
        ),
    ]
