# Generated by Django 5.2.3 on 2025-07-05 10:35

import api.models.contactus
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactUs',
            fields=[
                ('id', models.CharField(default=api.models.contactus.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(max_length=320)),
                ('city', models.CharField(blank=True, max_length=50, null=True)),
                ('zip', models.CharField(max_length=10)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'contact_us',
            },
        ),
    ]
