# Generated by Django 5.2.3 on 2025-06-26 09:28

import api.models.deliverychallan
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.CharField(default=api.models.deliverychallan.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('challan_number', models.CharField(max_length=50, unique=True)),
                ('date', models.DateField()),
                ('customer_name', models.CharField(max_length=100)),
                ('customer_address', models.TextField()),
                ('items', models.TextField(help_text='JSON or comma-separated list of items')),
                ('total_quantity', models.PositiveIntegerField()),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
            ],
            options={
                'db_table': 'delivery_challan',
            },
        ),
    ]
