# Generated by Django 5.2.3 on 2025-07-05 10:39

import api.models.deliverychallan
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryChallan',
            fields=[
                ('id', models.CharField(default=api.models.deliverychallan.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False)),
                ('challan_number', models.CharField(db_index=True, editable=False, max_length=20, unique=True)),
                ('date', models.DateField(default=datetime.date.today)),
                ('customer', models.CharField(max_length=200)),
                ('dc_summary', models.TextField(blank=True)),
                ('delivery_executives', models.TextField(blank=True)),
                ('invoice_number', models.CharField(blank=True, max_length=50, null=True)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('invoice_submission', models.BooleanField(default=False)),
                ('proof_of_delivery', models.FileField(blank=True, null=True, upload_to='proof_of_delivery/')),
                ('pod_entry_date', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Delivery Challan',
                'verbose_name_plural': 'Delivery Challans',
                'db_table': 'delivery_challan',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['date'], name='delivery_ch_date_810292_idx'), models.Index(fields=['customer'], name='delivery_ch_custome_913e3f_idx'), models.Index(fields=['created_at'], name='delivery_ch_created_7b8252_idx')],
            },
        ),
    ]
