# Generated by Django 5.2.3 on 2025-07-05 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deliverychallan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverychallan',
            old_name='pod_entry_date',
            new_name='pod_upload_date',
        ),
    ]
