# Generated by Django 5.2.3 on 2025-07-03 19:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_deliverychallan'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverychallan',
            old_name='customer_name',
            new_name='customer',
        ),
        migrations.RenameField(
            model_name='deliverychallan',
            old_name='customer_address',
            new_name='dc_summary',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='items',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='remarks',
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='total_quantity',
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='acknowledgement_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('acknowledged', 'Acknowledged')], default='pending', max_length=32),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='delivery_executives',
            field=models.TextField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='invoice_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='challan_number',
            field=models.CharField(editable=False, max_length=16, unique=True),
        ),
    ]
