# Generated by Django 5.2.3 on 2025-07-04 19:39

import api.models.deliverychallan
import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_customer_name_deliverychallan_customer_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverychallan',
            options={'ordering': ['-date', '-created_at'], 'verbose_name': 'Delivery Challan', 'verbose_name_plural': 'Delivery Challans'},
        ),
        migrations.RemoveField(
            model_name='deliverychallan',
            name='acknowledgement_status',
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='acknowledgement_copy',
            field=models.FileField(blank=True, help_text='Scanned copy or image of the signed acknowledgement (optional)', null=True, upload_to='acknowledgement_copies/'),
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='Timestamp when challan was created'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='deliverychallan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, help_text='Timestamp when challan was last updated'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='challan_number',
            field=models.CharField(db_index=True, editable=False, help_text='Auto-generated challan number in format YYMM####', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='customer',
            field=models.CharField(help_text='Name of the customer', max_length=200),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='date',
            field=models.DateField(default=datetime.date.today, help_text='Date of challan creation'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='dc_summary',
            field=models.TextField(blank=True, help_text='Summary of items being delivered'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='delivery_executives',
            field=models.TextField(blank=True, help_text='Names of delivery executives assigned'),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='id',
            field=models.CharField(default=api.models.deliverychallan.generate_uuid_hex, editable=False, help_text='Unique identifier for the delivery challan', max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='invoice_date',
            field=models.DateField(blank=True, help_text='Date when invoice was generated', null=True),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='invoice_number',
            field=models.CharField(blank=True, help_text='Invoice number if generated', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliverychallan',
            name='invoice_submission',
            field=models.BooleanField(default=False, help_text='Whether invoice has been submitted'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['date'], name='delivery_ch_date_810292_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['customer'], name='delivery_ch_custome_913e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['created_at'], name='delivery_ch_created_7b8252_idx'),
        ),
    ]
