# Generated by Django 5.2.3 on 2025-07-05 10:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_rename_pod_entry_date_deliverychallan_pod_upload_date'),
    ]

    operations = [
        migrations.RunSQL(
            sql="""
ALTER TABLE delivery_challan
    MODIFY COLUMN id varchar(32) NOT NULL,
    MODIFY COLUMN challan_number varchar(20) NOT NULL UNIQUE AFTER id,
    MODIFY COLUMN date date AFTER challan_number,
    MODIFY COLUMN customer varchar(200) AFTER date,
    MODIFY COLUMN dc_summary longtext AFTER customer,
    MODIFY COLUMN delivery_executives longtext AFTER dc_summary,
    MODIFY COLUMN invoice_number varchar(50) NULL AFTER delivery_executives,
    MODIFY COLUMN invoice_date date NULL AFTER invoice_number,
    MODIFY COLUMN invoice_submission tinyint(1) NOT NULL AFTER invoice_date,
    MODIFY COLUMN proof_of_delivery longblob NULL AFTER invoice_submission,
    MODIFY COLUMN pod_upload_date datetime NULL AFTER proof_of_delivery,
    MODIFY COLUMN created_at datetime(6) NOT NULL AFTER pod_upload_date,
    MODIFY COLUMN updated_at datetime(6) NOT NULL AFTER created_at;
            """,
            reverse_sql=migrations.RunSQL.noop,
        ),
    ]
