# Generated by Django 5.2.3 on 2025-07-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rbac', '0002_rename_all_tables'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='permission',
            table='rbac_permissions',
        ),
        migrations.AlterModelTable(
            name='role',
            table='rbac_roles',
        ),
        migrations.AlterModelTable(
            name='rolepermission',
            table='rbac_role_permissions',
        ),
        migrations.AlterModelTable(
            name='userrole',
            table='rbac_user_roles',
        ),
    ]
