# Generated by Django 5.2.3 on 2025-07-17 17:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('foursyz', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='foursyz',
            table='foursyz',
        ),
    ]
