# Generated by Django 5.2.3 on 2025-07-15 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_challan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='deliverychallan',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('delivered', 'Delivered'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
    ]
