# Generated by Django 5.2.3 on 2025-07-16 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_challan', '0002_alter_deliverychallan_status'),
        ('details_clients', '0003_alter_client_options'),
        ('details_mycompany', '0003_alter_company_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='deliverychallan',
            options={'ordering': ['challan_number'], 'verbose_name': 'Delivery Challan', 'verbose_name_plural': 'Delivery Challans'},
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['challan_number'], name='challan_number_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['company', 'status'], name='challan_company_status_idx'),
        ),
        migrations.AddIndex(
            model_name='deliverychallan',
            index=models.Index(fields=['delivery_date'], name='challan_delivery_date_idx'),
        ),
        migrations.AddConstraint(
            model_name='deliverychallan',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='positive_quantity'),
        ),
        migrations.AddConstraint(
            model_name='deliverychallan',
            constraint=models.CheckConstraint(condition=models.Q(('unit_price__gte', 0)), name='positive_unit_price'),
        ),
    ]
