# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_challan', '0003_alter_deliverychallan_options_and_more'),
        ('details_clients', '0004_remove_client_company'),
        ('details_mycompany', '0003_alter_company_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='DeliveryChallan',
            new_name='delivery_challan',
        ),
    ]
