# Generated by Django 5.2.3 on 2025-07-16 07:33

import datetime
import django.db.models.deletion
import non_public.delivery_challan.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_challan', '0004_rename_deliverychallan_delivery_challan'),
        ('details_clients', '0005_rename_client_details_clients'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='delivery_challan',
            name='positive_quantity',
        ),
        migrations.RemoveConstraint(
            model_name='delivery_challan',
            name='positive_unit_price',
        ),
        migrations.RemoveIndex(
            model_name='delivery_challan',
            name='challan_company_status_idx',
        ),
        migrations.RemoveIndex(
            model_name='delivery_challan',
            name='challan_delivery_date_idx',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='company',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='delivery_address',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='delivery_date',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='product_name',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='product_sku',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='quantity',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='total_price',
        ),
        migrations.RemoveField(
            model_name='delivery_challan',
            name='unit_price',
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='customer',
            field=models.CharField(default='DELETED', max_length=200),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='date',
            field=models.DateField(default=datetime.date.today),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='dc_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='delivery_executives',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='invoice_submission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='pod_upload_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='delivery_challan',
            name='proof_of_delivery',
            field=models.FileField(blank=True, null=True, upload_to='proof_of_delivery/'),
        ),
        migrations.AlterField(
            model_name='delivery_challan',
            name='challan_number',
            field=models.CharField(db_index=True, editable=False, max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='delivery_challan',
            name='client',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challans', to='details_clients.details_clients'),
        ),
        migrations.AlterField(
            model_name='delivery_challan',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_challans', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='delivery_challan',
            name='id',
            field=models.CharField(default=non_public.delivery_challan.models.generate_uuid_hex, editable=False, max_length=32, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='delivery_challan',
            index=models.Index(fields=['client', 'status'], name='challan_client_status_idx'),
        ),
        migrations.AddIndex(
            model_name='delivery_challan',
            index=models.Index(fields=['date'], name='challan_date_idx'),
        ),
    ]
