# Generated by Django 5.2.3 on 2025-07-16 07:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_challan', '0005_remove_delivery_challan_positive_quantity_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='delivery_challan',
            name='customer',
        ),
        migrations.AlterField(
            model_name='delivery_challan',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_challans', to='details_clients.details_clients'),
        ),
        migrations.AlterField(
            model_name='delivery_challan',
            name='created_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_challans', to='auth.user'),
        ),
    ]
