# Generated by Django 5.2.3 on 2025-07-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries_mycompany', '0002_alter_query_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='query',
            options={'ordering': ['-created_at'], 'verbose_name_plural': 'Queries'},
        ),
    ]
