# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details_clients', '0005_rename_client_details_clients'),
        ('details_mycompany', '0004_rename_company_details_mycompany'),
        ('queries_mycompany', '0003_alter_query_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Query',
            new_name='queries_mycompany',
        ),
    ]
