# Generated by Django 5.2.3 on 2025-07-16 04:17

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_clients', '0003_alter_client_options'),
        ('details_mycompany', '0003_alter_company_options_and_more'),
        ('products', '0002_alter_clientproductassignment_table_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientproductassignment',
            options={'ordering': ['-assigned_at'], 'verbose_name': 'Client Product Assignment', 'verbose_name_plural': 'Client Product Assignments'},
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['name'], 'verbose_name': 'Product', 'verbose_name_plural': 'Products'},
        ),
        migrations.AddIndex(
            model_name='clientproductassignment',
            index=models.Index(fields=['client', 'is_active'], name='client_product_active_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['sku'], name='product_sku_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['company', 'is_active'], name='product_company_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.CheckConstraint(condition=models.Q(('price__gte', 0)), name='positive_price'),
        ),
    ]
