# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details_clients', '0005_rename_client_details_clients'),
        ('details_mycompany', '0004_rename_company_details_mycompany'),
        ('products', '0003_alter_clientproductassignment_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Product',
            new_name='products',
        ),
        migrations.RenameModel(
            old_name='ClientProductAssignment',
            new_name='products_clientproductassignment',
        ),
    ]
