# Generated by Django 5.2.3 on 2025-07-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries_clients', '0002_alter_clientquery_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='clientquery',
            options={'ordering': ['-created_at']},
        ),
    ]
