# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('queries_clients', '0003_alter_clientquery_options'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ClientQuery',
            new_name='queries_clients',
        ),
    ]
