# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MessageThread',
            new_name='message_thread',
        ),
        migrations.RenameModel(
            old_name='NotificationLog',
            new_name='notification_log',
        ),
        migrations.RenameModel(
            old_name='NotificationPreference',
            new_name='notification_preference',
        ),
        migrations.RenameModel(
            old_name='NotificationTemplate',
            new_name='notification_template',
        ),
    ]
