# Generated by Django 5.2.3 on 2025-07-15 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details_clients', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='client',
            table='details_clients',
        ),
    ]
