# Generated by Django 5.2.3 on 2025-07-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details_clients', '0002_alter_client_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='client',
            options={'ordering': ['name']},
        ),
    ]
