# Generated by Django 5.2.3 on 2025-07-16 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('details_clients', '0003_alter_client_options'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='client',
            name='company',
        ),
    ]
