# Generated by Django 5.2.3 on 2025-07-16 05:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('delivery_challan', '0004_rename_deliverychallan_delivery_challan'),
        ('details_clients', '0004_remove_client_company'),
        ('products', '0003_alter_clientproductassignment_options_and_more'),
        ('queries_mycompany', '0003_alter_query_options'),
        ('users_mycompany', '0003_alter_userprofile_options'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Client',
            new_name='details_clients',
        ),
    ]
