# Generated by Django 5.2.3 on 2025-07-16 04:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users_mycompany', '0002_alter_userprofile_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-created_at', 'user__username']},
        ),
    ]
