# Generated by Django 5.2.3 on 2025-07-15 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('email_domain', models.CharField(max_length=100, unique=True)),
                ('short_name', models.CharField(max_length=50, unique=True)),
                ('address', models.TextField()),
                ('phone', models.CharField(max_length=20)),
                ('website', models.URLField(blank=True)),
                ('logo', models.ImageField(blank=True, upload_to='company_logos/')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Companies',
                'db_table': 'company',
            },
        ),
    ]
