# Generated by Django 5.2.3 on 2025-07-16 04:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_mycompany', '0002_alter_company_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='company',
            options={'ordering': ['name'], 'verbose_name': 'Company', 'verbose_name_plural': 'Companies'},
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['email_domain'], name='company_email_domain_idx'),
        ),
        migrations.AddIndex(
            model_name='company',
            index=models.Index(fields=['short_name'], name='company_short_name_idx'),
        ),
        migrations.AddConstraint(
            model_name='company',
            constraint=models.CheckConstraint(condition=models.Q(('is_active__in', [True, False])), name='valid_company_status'),
        ),
    ]
