# Generated by Django 5.2.3 on 2025-07-16 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('details_mycompany', '0004_rename_company_details_mycompany'),
    ]

    operations = [
        migrations.AddField(
            model_name='details_mycompany',
            name='is_permanent',
            field=models.BooleanField(default=False, help_text="This record cannot be deleted and ensures there's always one company record"),
        ),
        migrations.AddIndex(
            model_name='details_mycompany',
            index=models.Index(fields=['is_permanent'], name='company_permanent_idx'),
        ),
    ]
